N_t: 25
N_k: 50
gamma: 1.0
lambda_: 0.6
sigma_u0: 10.0
sigma_u: 5.0
sigma_filter_u: 8.0
dt: 0.01

Qpos: {'x': 1.0, 'y': 1.0, 'z': 10.0}
Qpower: 0.0
Qobs: 55.0

filter_control: true
use_traj_horizon: false
project_goal: false
normalize_costs: false
use_wind: false
adapt_goal: false
twod: false